### ISSUE TITLE
id_ref_df 

### ISSUE THREAD

**Issue by AparajithaRamesh** [AparajithaRamesh/pondr#6]
**Input** = id_ref_df. This is the reference dataframe that users have with ID of each individual being tested for the given experiment, with any other columns. This needs to be formatted as follows
- Simplest case: vector of individual PIT tag ID of all individuals named "id" 

- Dataframe with all with individual PIT tag ID as first column, label it "id" and can have other variables (size , sex, parent ...)

**Comment by BenKawam** [comment]
So far, we have a list of reference individuals and their corresponding covariates for the full dataset (e.g., all the ponds), but we also need a reference data frame per experimental block (e.g. pond). Actually, I think it is _mostly_ useful at the experimental block level, if, for instance, we have read 18/25 individuals in a pond and we need a reference list to know who's missing.

I guess we have two choices:

1. We import one reference data frame per experimental block.
2. We import a reference data frame for all the blocks, and subset part of them subsequently, e.g. when computing the _pr_filter_ function. 
1. 

1. 

1. 

1.
